language: python
python:
- '3.5'
- '3.6'
install:
- pip install -e .[test]
script:
- python -m "nose"
deploy:
  provider: pypi
  user: mike_burn
  password:
    secure: "XD+8uaDpF53bJEkI5KWwjPu682N8snfGUJ+2odh9R7mS2baCDhzFrR2l/KI3iRWP4XlJoEAJyGBUMoC172zHswYPSUBMzKM8ZZImdwQnIBbyDjVodwe//ZleL+9xmb7A1PeC8u/1k65NLpkaJgG6CK0l6TxW2mAmvbiQ1D4I641+eUR7uSrPccwkS2K6qe2q/Hl4lcNLL3jeIYpXabF+18OiXhjF+nAirfvRC1FNhwFyO9owAyXh6mw1DVaCP4xPALO2mc9sje3Aj1Nqf9VBO4NhNgJvJaze8whpssN1VOLWcGHJpd5sYADwzKRrsloM//WRwpJS2KonzmvDlLnEjfK+Oj5Vb2xaXH1le5tfGQLPqZ4R5c4CnLBigW2EYOOxI50d+wh/49wFkVa0h5XQ7Xw92qA8X1nJpnfZlXtv3JUUa8FmJiUWHKYh79Q7WO/5YihAlbRJJYzX3zHMJ4zGwVfHIMitqOzCqKysg/JbpNHH8REI7E+LcZlXLuIxF3prjDNAiqAhDFGmUC4IFPdFw78c8ip9YlvVFarJQOhGHVpHxe2n0fuJRRSDyofAjZuwH1dJmjZsDqFQBKRfw/6PVbNGTZsVoaIFIws4CvsBRlrrJE/g32Xn4gtwh87PeqBDja1Ta73SQwu4GLzhDklwhyRtp9l8RAJTy/sdAW/caAI="
  on:
    branch: master
    python: '3.6'
