language: python
python:
- '3.5'
- '3.6'
install:
- pip install -e .[test]
script:
- python -m "nose"
deploy:
  provider: pypi
  user: mike_burn
  password:
    secure: HfMnNNjGes37siip7/skcJNqJTnhdXTsBuFdlWydw8iIiwh1cnODHD/9LzdAx6V8B3i2XjNpd/zoQzgKkGFV845Uewu9YUX99lqSY422/RjlnUcOBYo5Uo1RXuOaBnMM9QRSu/axwvWyQbBAgUu8sFfjEn447CFEMJq7ywnTi5a+Kd8am34WvoEbeTmVW4rI1Gp6QpaEoZEVaM7uLVbC62ltE71PeY8xV7WQFf1kyeo/qBtP3MMKDmBsW12HwUEVZtqiIzemRlho3npuONd72Wkz8PppJ/qkUWjmxRfsiQcJRI3zJXPxVwiIhvA+sGvQYf/CkBWiDuUtT3wVBTUVSTthAC65Neq7BzdXnSWWYJkk98LfU/Vt3+rwmdrFV4dxs1sVorSfD4GLow6SPY/mfoIjutKYWRUe+rvbryktYEA1Jpbu4B01KdTiYEmtg22W18sBjYcvCk1GRbws5UAcgp08ScR5+NymLdOsx4AZeztEKhUXqumc+X4XYJcq3wr4g7dPV228cs144B6Yzhi3v7/kWTKh+DhtRE/3urqQ4e/XlrZwX5tjJyMfQaIqmE9uBTmRW6r1OgOWqvjWevy08N1TYG/ox7dbVHC8iS6DTS6XQ9b5vwXZzXRKbprEq9zFuyaJjAF0a1EGDNHFWicnaHwDD2a0TvNaUieEM30FlTo=
  on:
    branch: master
